name: Maven CI

on:
  push:
    branches:
      - 'main'
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
#      - '.github/**'
      - '.gitignore'
      - 'attribute.txt'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'INDIVIDUAL_CONTRIBUTOR_LICENSE.md'
      - 'LICENSE'
      - 'NOTICE.txt'
      - '**/README.md'
  pull_request:
    branches:
      - 'main'
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
#      - '.github/**'
      - '.gitignore'
      - 'attribute.txt'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'INDIVIDUAL_CONTRIBUTOR_LICENSE.md'
      - 'LICENSE'
      - 'NOTICE.txt'
      - '**/README.md'

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build Java
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Maven Prepare
        id: maven-prepare
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version-file: .tool-versions
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Build Maven Project
        if: success() && (github.event_name == 'pull_request')
        run: ./mvnw --batch-mode install -D ci.build
      - name: Build Maven Project and Deploy to Sonatype OSSRH
        if: success() && (github.event_name == 'push')
        run: ./mvnw --batch-mode deploy -D ci.deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Publish Test Report
        if: always()
        continue-on-error: true
        uses: dorny/test-reporter@v2
        with:
          name: Test Report - Java
          path: '**/target/(surefire|failsafe)-reports/TEST-*.xml'
          reporter: java-junit
